import "./globals.css";
import { Providers } from "./providers";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Fitness Coach",
  description: "Personalized workout and diet plans generated by Gemini",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // suppressHydrationWarning is essential when using Chakra UI with Next.js App Router
    <html lang="en" suppressHydrationWarning>
      <head />
      <body suppressHydrationWarning>
        <Providers>
          <div
            style={{
              minHeight: "100vh",
              background: "linear-gradient(180deg,#06071a 0%, #0b0f1a 100%)",
            }}
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
