import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { GeneratedPlan } from "@/lib/types";

/**
 * Create a styled HTML snapshot and convert to PDF.
 * Returns a Blob.
 */
export async function exportPlanToPdf(plan: GeneratedPlan): Promise<Blob> {
  // Build an off-screen container
  const container = document.createElement("div");
  container.style.width = "900px";
  container.style.padding = "28px";
  container.style.background = "#0f1724"; // dark background
  container.style.color = "#e6eef8";
  container.style.fontFamily =
    "Inter, Roboto, system-ui, -apple-system, 'Segoe UI', sans-serif";
  container.style.lineHeight = "1.4";
  container.style.borderRadius = "8px";

  // Header
  const header = document.createElement("div");
  header.innerHTML = `<div style="display:flex;justify-content:space-between;align-items:center;">
    <div>
      <h1 style="margin:0;font-size:22px;color:#fff">AI Fitness Plan</h1>
      <div style="color:#9aa7b2;margin-top:6px">Personalized by Gemini • Generated by AI</div>
    </div>
    <div style="text-align:right;color:#9aa7b2">
      <div>Generated</div>
      <div style="font-weight:600">${new Date().toLocaleString()}</div>
    </div>
  </div><hr style="margin:12px 0;border:0;border-top:1px solid #213040" />`;
  container.appendChild(header);

  if (plan.summary) {
    const p = document.createElement("p");
    p.style.color = "#cfe7ff";
    p.style.marginTop = "8px";
    p.textContent = plan.summary;
    container.appendChild(p);
  }

  // Workout section
  const workoutSec = document.createElement("div");
  workoutSec.innerHTML = `<h2 style="color:#cfe7ff;margin-bottom:8px">Workout</h2>`;
  plan.workout.forEach((d) => {
    const dayBox = document.createElement("div");
    dayBox.style.marginBottom = "8px";
    dayBox.innerHTML = `<div style="font-weight:700;color:#fff">${d.day}</div>`;
    const ul = document.createElement("ul");
    ul.style.margin = "6px 0 0 16px";
    d.exercises.forEach((ex: any) => {
      const li = document.createElement("li");
      li.style.marginBottom = "4px";
      li.innerHTML = `<span style="font-weight:600">${ex.name}</span> — ${ex.sets} sets ${ex.reps ? `• ${ex.reps} reps` : ""} • rest ${ex.rest_seconds ?? 60}s`;
      ul.appendChild(li);
    });
    dayBox.appendChild(ul);
    workoutSec.appendChild(dayBox);
  });
  container.appendChild(workoutSec);

  // Diet section
  const dietSec = document.createElement("div");
  dietSec.style.marginTop = "12px";
  dietSec.innerHTML = `<h2 style="color:#cfe7ff;margin-bottom:8px">Diet</h2>`;
  const sections = ["breakfast", "lunch", "dinner", "snacks"];
  (sections as Array<keyof typeof plan.diet>).forEach((key) => {
    const arr = (plan.diet as any)[key];
    if (!arr || !arr.length) return;
    const div = document.createElement("div");
    div.style.marginBottom = "8px";
    div.innerHTML = `<div style="font-weight:700;color:#fff">${key.charAt(0).toUpperCase() + key.slice(1)}</div>`;
    const ul = document.createElement("ul");
    ul.style.margin = "6px 0 0 16px";
    arr.forEach((m: any) => {
      const li = document.createElement("li");
      li.style.marginBottom = "4px";
      li.textContent = `${m.name}${m.calories ? ` — ${m.calories} kcal` : ""}`;
      ul.appendChild(li);
    });
    div.appendChild(ul);
    dietSec.appendChild(div);
  });
  container.appendChild(dietSec);

  if (plan.tips && plan.tips.length) {
    const tips = document.createElement("div");
    tips.style.marginTop = "12px";
    tips.innerHTML = `<h3 style="color:#cfe7ff;margin-bottom:8px">Tips</h3>`;
    const ul = document.createElement("ul");
    ul.style.margin = "6px 0 0 16px";
    plan.tips.forEach((t) => {
      const li = document.createElement("li");
      li.textContent = t;
      li.style.marginBottom = "6px";
      ul.appendChild(li);
    });
    tips.appendChild(ul);
    container.appendChild(tips);
  }

  // Attach to DOM, render to canvas
  document.body.appendChild(container);
  const canvas = await html2canvas(container as HTMLElement, {
    scale: 2,
    backgroundColor: null,
  });
  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({
    unit: "px",
    format: [canvas.width, canvas.height],
  });
  pdf.addImage(imgData, "PNG", 0, 0, canvas.width, canvas.height);
  const blob = pdf.output("blob");
  document.body.removeChild(container);
  return blob;
}
